### ISSUE TITLE
Storing read logs in cache

### ISSUE THREAD

**Issue by garygreen** [stevebauman/log-reader#1]
Probably a bad idea as the cache could easily be flushed. Would be nice to store it in a more permanent place (maybe in database) .

**Comment by stevebauman** [comment]
That's true, however that would mean storing all log entries in the database, but that's not a bad idea either. I'll work this in.

**Comment by garygreen** [comment]
Well you could make it generic to store and retrieve logs through a repository -- that way users can implement their own repository if they like (maybe to store logs in ElasticSearch or Redis, etc).

```php
LogReader::addStorage('elasticsearch', 'App\LogReader\ElasticSearchRepository');
LogReader::storage('elasticsearch')->get();
```

**Comment by stevebauman** [comment]
This is true, but how can I go about watching the logs for changes so they can be stored permanently in another repository?

I thought about catching the global `illuminate.log` event inside the Log writer: https://github.com/laravel/framework/blob/5.1/src/Illuminate/Log/Writer.php#L295. However, it seems that the event can only be caught when you use logging directly, for example: `Log::info('Exception');`. Exceptions that generate logs don't seem to be able to be listened to, at least from my experimentation.

I could import / sync the logs when the entries are retrieved from the files themselves, but that's definitely resource intensive and probably unnecessary. Would you happen to have any suggestions?

**Comment by garygreen** [comment]
Well you could use some of the handlers available already in monolog like `RedisHandler` -- or a custom create an `EloquentHandler` which will catch exceptions and log to database in a known format.

The tricky part is pulling the data back out in a standard format. I'm not sure what kind of format the RedisHandler or other built in monolog handlers store in, but I assume it's pretty standardised.

**Comment by stevebauman** [comment]
That's true, but I'd also have to implement a Log handler as well to pull in all other log entries that use `Log::info(); Log::error();` etc.

To be honest, I'm not sure if this is the way to go. I'd have to completely swap out the current implementation (parsing the log files), to multiple handlers (a global exception handler, and a global log event listener) which devs would need to insert into their `EventServiceProvider`, that would then store the log entries in a (hopefully) standardized way in possibly multiple repository types.

This is doable, but it's definitely going to be extremely tricky to implement. This package would then be more of a "Log Storage" rather than a "Log Reader".

**Comment by stevebauman** [comment]
Scratch all that, you're right about adding a monolog handler. Implementing now

**Comment by stevebauman** [comment]
Updated to `v1.1.0`, added eloquent log handler, and added the ability to easily add your own custom handlers in configuration as well as customize the eloquent handler model.
